import type { Airport, Flight } from "../src/types";
export const evn: Airport = {
  id: "UDYZ",
  iata: "EVN",
  icao: "UDYZ",
  name: "Zvartnots International Airport",
  city: "Yerevan",
  country: "AM",
  countryName: "Armenia",
  lat: 40.1473,
  lon: 44.3959,
  elevation: 2838,
  tz: "Asia/Yerevan",
  type: "large_airport",
};
export const lca: Airport = {
  id: "LCLK",
  iata: "LCA",
  icao: "LCLK",
  name: "Larnaca International Airport",
  city: "Larnaca",
  country: "CY",
  countryName: "Cyprus",
  lat: 34.8751,
  lon: 33.6249,
  elevation: 8,
  tz: "Asia/Nicosia",
  type: "large_airport",
};
export function flight(patch: Partial<Flight> = {}): Flight {
  return {
    id: crypto.randomUUID(),
    number: "TEST101",
    airline: "Test airline",
    origin: evn,
    destination: lca,
    scheduledDeparture: "2025-01-02T20:00:00Z",
    scheduledArrival: "2025-01-02T22:00:00Z",
    actualDeparture: "",
    actualArrival: "",
    estimatedDeparture: "",
    estimatedArrival: "",
    status: "Completed",
    model: "",
    registration: "",
    icao24: "",
    evidence: "",
    seat: "",
    cabin: "",
    notes: "",
    source: "user",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-01-01T00:00:00Z",
    ...patch,
  };
}
